version: '3.8'

services:
  config-service:
    build:
      context: ./config-service
      dockerfile: Dockerfile
    image: myorg/config-service:latest
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=native
    volumes:
      - ./configurations:/configurations